# Generated by Django 5.0.2 on 2024-03-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.PositiveIntegerField(blank=True, default=91028595914),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('FootWear', 'FootWear'), ('Watches', 'Watches')], max_length=50),
        ),
    ]
