# Generated by Django 5.0.2 on 2024-03-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_order_transaction_id_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.PositiveIntegerField(blank=True, default=72107094816),
        ),
    ]
