# Generated by Django 5.0.2 on 2024-03-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_product_product_available_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.PositiveIntegerField(blank=True, default=82476150977),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('FootWear', 'FootWear'), ('Watches', 'Watches'), ('Sun Glassess', 'Sun Glassess')], max_length=50),
        ),
    ]
