# Generated by Django 5.0.2 on 2024-03-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewofproduct',
            name='review_user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.PositiveIntegerField(blank=True, default=26425870287),
        ),
    ]
