# Generated by Django 5.0.2 on 2024-03-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_reviewofproduct_review_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.PositiveIntegerField(blank=True, default=35482067006),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Shirts', 'Shirts'), ('FormalMen', 'FormalMen'), ('FormalWomen', 'FormalWomen'), ('Groom', 'Groom'), ('Bridal', 'Bridal'), ('Jeans', 'Jeans'), ('FootWear', 'FootWear'), ('Watches', 'Watches'), ('Sun Glassess', 'Sun Glassess')], max_length=50),
        ),
    ]
