# Generated by Django 5.0.2 on 2024-03-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_order_product_alter_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproduct',
            name='return_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.PositiveIntegerField(blank=True, default=583773384),
        ),
    ]
