# Generated by Django 5.0.2 on 2024-03-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_returnproduct_return_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnproduct',
            name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.PositiveIntegerField(blank=True, default=54072464690),
        ),
    ]
