# Generated by Django 5.0.2 on 2024-03-08 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_returnproduct_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproduct',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.PositiveIntegerField(blank=True, default=31969726603),
        ),
    ]
