# Generated by Django 5.0.2 on 2024-03-08 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_order_transaction_id_alter_returnproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.PositiveIntegerField(blank=True, default=2074076993),
        ),
        migrations.AlterField(
            model_name='returnproduct',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.order'),
        ),
    ]
