from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    home,
    CategoryVIEW,
    CategoryTitleView,
    ProductDetailsVIEW,
    about,
    contact,
    CustomerRegistrationVIEW,
    UserProfile,
    UserProfileAddress,
    UserAddressView,
    UpdateAddressView,
    DeleteAddressView,
    AddToCart,
    Show_Cart,
    Remove_Cart_Item,
    Order_DetailsView,
    SuccessOrder,
    orderReciptView,
    OrdersView,
    otp_verification,
    minus_wishlist,
    plus_wishlist,
    WishList,
    Buy_Now,
    Direct_Buy_Order_DetailsView,
    search_items,
    ProfileData,
    UpdateProfileData,
    CustomerQuerySave,
    AddProductView,
    ViewProducts,
    UpdateProducts,
    ProductDelete,
    productsForMen,
    mensProductFilter,
    productsForwoMen,
    womensProductFilter,
    AddProductReviewView,
    AllReviewsOfAProductView,
    add_Review_After_buying,
    ProductReturnFormView
)
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view
from .forms import UserLoginForm,PasswordChangeForm

urlpatterns = [
    path('', home,name='home'),
    # Register,Login and Logout Views with custom forms
    path("registration/",CustomerRegistrationVIEW.as_view(),name='registration'),
    path("login/",auth_view.LoginView.as_view(template_name = 'login.html',authentication_form = UserLoginForm),name='login'),
    path("passwordChange/",auth_view.PasswordChangeView.as_view(template_name = 'changepassword.html',form_class = PasswordChangeForm,success_url = '/passwordchangedone'),name='passwordchange'),
    path("passwordchangedone/",auth_view.PasswordChangeDoneView.as_view(template_name = 'changepassworddone.html'),name='passwordchangedone'),
    path('logout/',auth_view.LogoutView.as_view(next_page='login'),name='logout'),
    # Other Views
    path('profile/',UserProfile.as_view(),name='profile'),
    path('profile_data/',ProfileData.as_view(),name='profile_data'),
    path('update_profile_data/<int:id>',UpdateProfileData.as_view(),name='update_profile_data'),
    path('add_address/',UserProfileAddress.as_view(),name='add_address'),
    path('address/',UserAddressView.as_view(),name='address'),
    path('update_address/<int:id>',UpdateAddressView.as_view(),name='update_address'),
    path('delete_address/<int:id>',DeleteAddressView.as_view(),name='delete_address'),
    path('category/<str:val>',CategoryVIEW.as_view(),name='category'),
    path('about/',about,name='about'),
    path('contact/',contact,name='contact'),
    path('addproduct/',AddProductView.as_view(),name='add_product'),
    path('updateproducts/<int:id>',UpdateProducts.as_view(),name='update_products'),
    path('viewproduct/',ViewProducts,name='view_products'),
    path('productformen/',productsForMen,name='men_products'),
    path('mensproductfilter/<str:type>',mensProductFilter,name='mensproductfilter'),
    path('productforwomen/',productsForwoMen,name='women_products'),
    path('womensproductfilter/<str:type>',womensProductFilter,name='womensproductfilter'),
    path('deleteproduct/<int:id>',ProductDelete,name='delete_products'),
    path('category_title/<str:val>',CategoryTitleView.as_view(),name='category-title'),
    path('product_details/<int:pk>',ProductDetailsVIEW.as_view(),name='product-details'),
    path('addtocart/<int:prod_id>',AddToCart,name='addtocart'),
    path('showcart/',Show_Cart,name='show_cart'),
    path('buynow/<int:id>',Buy_Now,name='buynow'),
    path('removefromcart/<int:id>',Remove_Cart_Item,name='removecartitem'),
    path('orderdetails/',Order_DetailsView.as_view(),name='orderdetails'),
    path('directbuyorderdetails/<int:id>',Direct_Buy_Order_DetailsView.as_view(),name='directbuyorderdetails'),
    path('ordersuccess/',SuccessOrder,name='ordersuccess'),
    path('orderrecipt/',orderReciptView,name='orderrecipt'),
    path('verification/',otp_verification,name='verification'),
    path('orderview/',OrdersView.as_view(),name='orderview'),
    path('productreturnformview/',ProductReturnFormView,name='productreturnformview'),
    path("pluswishlist/",plus_wishlist),
    path('minuswishlist/',minus_wishlist),
    path('wishlist/',WishList,name='wishlist'),
    path('searchproducts/',search_items,name='searchproducts'),
    path('addreview/<int:id>',AddProductReviewView.as_view(),name='addreview'),
    path('reviewsofaproduct/<int:id>',AllReviewsOfAProductView,name='reviewsofaproduct'),

    path('addreviewtoorderproduct/<int:id>',add_Review_After_buying,name='addreviewtoorderproduct'),

    path('customerquerysave/',CustomerQuerySave,name='customerquerysave'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)